/**
 * @name 字段
 */
import btnText from './btnText';
import global from './global';

export const fieldBehavior = {
  default: {
    noExistForItemType: `{{text}}类型已经不存在了`,
    fieldBehavior: '字段行为',
    customField: '自定义字段',
    addField: '新建字段',
    delField: '该字段已被删除',
    fieldBehaviorSetting: '字段配置',
    securityLevelConfig: '安全级别配置',
    screenOptions: {
      create: '新建界面',
      edit: '编辑界面',
      view: '查看界面',
    },
    yes: global.yes,
    no: global.no,
    noDefaultContent: '暂无默认内容',
    noCondition: '暂无条件行为',
    targetField: '目标字段',
    visibleContent: '可见内容',
    defaultContent: '默认内容',
    select: '请选择',
    addCondition: '添加条件',
    drawer: {
      title: '级联条件',
      field: '条件字段',
    },
    contionWarning: ['同时使用多种行为可能导致事项编辑完成后无法保存', '当以下设置的条件全部满足时，上述字段行为有效'],
    cascadeModalTip: '条件字段的值影响目标字段的可见内容和默认内容',
    configField: '配置字段行为',
    takeEffectCondition: '生效条件',
    applicationField: '应用字段',
    fieldsName: '字段名称',
    viewDoc: '查看说明文档',
    addFieldBehavior: '新建字段行为',
    description: '根据行为条件限制字段行为，可设置特定的字段行为方案',
    fieldBehaviorName: '字段行为名称',
    defaultBehavior: '默认行为',
    conditionBehavior: '条件行为',
    fieldCascade: '字段级联',
    addConditionBehavior: '添加条件行为',
    serverScript: '服务端脚本',
    addCascade: '添加级联条件',
    conditionBehaviorName: '条件行为（{{behaviorSetting?.field?.name}}）',
    cascadeColumns: '默认内容（{{behaviorSetting?.field?.name}}）',
    user: '用户',
    currentLoggedUser: '当前登录用户',
  },
  columns: {
    delField: '该字段已被删除',
    default: '默认行为',
    behaviorCount: '条件行为',
    cascadeCount: '字段依赖',
    // ---------------
    conditionList: '行为条件',
    readonly: '字段行为',
    action: '操作',
    name: '行为名称',
    itemTypeCount: '类型',
    status: '启用',
  },
  modal: {
    edit: {
      title: '编辑字段行为',
    },
    delete: {
      title: '删除',
      content: '确定删除此项吗？',
    },
    deleteFieldBehavior: {
      title: '删除字段行为',
      content: {
        query: '确定删除字段行为「{{name}}」吗？',
        tip: '删除后数据将不能恢复，请谨慎操作',
      },
    },
  },
  view: {
    configDefaultBehavior: '配置的字段在默认情况下的行为',
    configPriority: '配置的字段在指定条件下的行为，条件行为优先级高于默认行为。',
    configFieldCascade: '配置字段值之间的级联关系',
    mapItemType: '映射类型',
    mapItemTypeDesc: '将字段行为应用至被映射的类型，如未设置类型，则方案无法生效',
    addFieldBehavior: global.getBtnText(btnText.settings.fieldBehavior), // '新建字段行为',
  },
};

export const fields = {
  default: {
    addFilter: '添加筛选',
    haveDeleteThisComment: '该评论已删除',
    fieldTypeSet: '字段类型设置',
    insertItem: '创建事项',
    cloneItem: '复制事项',
    inProgress: '待确定',
    preVersion: '上一版本',
    thisVersion: '本版本',
    noConfiguration: '暂无配置',
    toWorkspacePage: '点击进入空间',
    createDataItem: '新建数据项',
    createItemTypeHierarchyScheme: '新建类型层级方案',
    itemId: 'Key',
    itemTitle: '事项标题',
    itemStatus: '事项状态',
    itemType: '类型',
    separator: '分隔符',
    placeholderStart: '占位提示（开始）',
    placeholderEnd: '占位提示（结束）',
    fieldDesc: '业务说明',
    TOOL_BAR_BUTTON_TIP: {
      ALIGN_LEFT: '左对齐',
      ALIGN_RIGHT: '右对齐',
      ALIGN_CENTER: '居中对齐',
      ELEMENT_HEADER: '标题',
      MARK_BOLD: '加粗',
      MARK_ITALIC: '倾斜',
      MARK_UNDERLINE: '下划线',
      MARK_BG_COLOR: '背景颜色',
      MARK_HIGHLIGHT: '文本高亮',
      MARK_STRIKETHROUGH: '删除线',
      MARK_FONT_SIZE: '字号',
      KEY_LINE_HEIGHT: '行高',
      MARK_COLOR: '字色',
      ELEMENT_OL: '有序列表',
      ELEMENT_UL: '无序列表',
      ELEMENT_TABLE: '插入表格',
      ELEMENT_IMAGE: '插入图片',
      ELEMENT_LINK: '超链接',
      MARK_CODE: '插入代码',
    },
    insertRecord: '新增数据',
    deleteRecord: '删除数据',
    uploadAgain: '重新上传',
    noAuth: '暂无查看权限',
    getImageError: '图片获取失败',
    noItemType: '未指定类型',
    addChildItem: '新建子事项',
    addItemLevel: '添加层级',
    relateItem: '关联事项',
    linkCards: '请选择待关联的工作项',
    maxRowsTip: '最大行数不能小于最小行数',
    maxRows: '最大行数',
    minRows: '最小行数',
    minRowsTip: '最小行数不能大于最大行数',
    maxLength: '最大输入长度',
    addonAfter: '{{value}}个字符',
    regular: '验证',
    property: global.config,
    verifyScript: '验证脚本',
    clear: '清空全部选项',
    addTag: '创建标签',
    submit: '完成创建',
  },
  group: {
    range: '筛选范围选项',
    other: '其他选项',
  },
  activity: {
    changeLog: '变更记录',
    comment: '评论',
    stateFlow: '状态流转',
    oldestFirst: '最旧优先',
    latestFirst: '最新优先',
  },
  modal: {
    deleteField: {
      title: '删除字段',
      content: {
        areYouSure: '确定删除字段「{{name}}」吗？',
      },
    },
    changeLog: {
      title: '{{editorField.field.name}} 变更记录 {{time}}',
    },
    delete: {
      title: '删除',
      removeItem: `确定要删除此项吗？`,
      column: '删除列',
      content: `确定删除该列吗？`,
      fieldType: '删除字段类型',
      contentField: `确定删除字段类型「{{name}}」吗？`,
    },
    create: {
      addColumn: '新增列',
      numberType: '字段类型',
      fieldType: '新建字段类型',
      title: '新建数据项',
    },
    edit: {
      title: '编辑数据项',
      column: '编辑列',
      fieldType: '编辑字段类型',
    },
    field: {
      create: '新建字段',
      edit: '编辑字段',
      configAdd: '确认并配置',
      submitAdd: '确定并继续创建',
    },
    deleteRelate: {
      title: '解除关联关系',
      content: '确定要解除事项的关联关系吗？',
    },
    changeParentItem: '更改父事项',
    itemHierarchy: '事项层级',
    removeItemHierarchy: '解除层级',
    viewFieldType: '查看字段类型',
    deleteHierarchy: {
      title: '解除事项层级',
      content: '解除后子事项将作为第一层级展示，是否继续解除?',
    },
    ADD_ITEMS: '新建关联事项',
    selectKey: '选择事项',
    selectLink: '选择关联',
    relieveLink: '解除关联',
    selectMoreItem: '选择更多事项',
    editPriority: '编辑优先级',
    flowChat: '流程图({{name}})',
  },
  columns: {
    label: '选项名',
    value: '选项值',
    color: '颜色',
    order: '排序',
    tagName: '标签名',
    link: {
      name: '标题',
      key: 'Key',
      workspace: '所属空间',
      itemType: '类型',
      status: '状态',
    },
  },
  view: {
    createFieldBtn: global.getBtnText(btnText.settings.field),
    headerActivity: '活动',
    cellConfig: '表格字段配置',
    maximumFileSize: '文件大小最大不能超过{{maximumFileSize}}MB',
    statusTextObj: {
      clone: '复制了事项',
      insert: '新建了事项',
      change: '变更了事项状态，历时{{time}}',
    },
    editAttributeText: '编辑了事项属性',
    viewUpdateLog: '查看变更记录',
    popconfirm: {
      queryDelete: '确认删除当前评论？',
      addComments: '添加评论',
    },
    uploadAnnex: '上传附件',
    uploadFile: '上传文件',
    modal: {
      annexTitle: '确定删除此附件？',
      fileTitle: '确定删除此文件？',
      content: '此删除操作不可恢复',
    },
    annex: '附件', // annex
    configOptionTip: ['暂未配置选项数据，请', '点击配置'],
    fieldCollectionTip: '编辑后点击保存按钮即可完成集合数据的变更',
    addColumnSchema: {
      fieldName: [
        '请输入列名称',
        '目前查询仅支持文字、数字、英文，且不能以数字开头，请检查修改',
        '请输入选项，限40个字符',
        '选项值有误（不能为空或重复）',
      ],
      fieldType: ['请选择列类型', '请至少添加一个选项'],
    },
    SelectableColumns: {
      SINGLE_SELECT: '单选',
      MULTIPLE_SELECT: '多选',
      DATE_TIME: '日期与时间',
      PURE_DATE: '日期',
      SINGLE_USER: '单个用户',
      MULTIPLE_USER: '多个用户',
      PURE_NUMBER: '数字',
      PURE_TEXT: '文本',
    },
    popText: '{{label}}是必填字段，无法删除，是否上传新的文件。',
    viewFormula: '查看公式',
    failInitializePlugin: '插件初始化失败',
    failRunningPlugin: '插件运行崩溃',
    noDependency: '暂无此依赖集成',
    removeBinding: '解除绑定',
    emptyPriority: '暂无可用优先级',
    noPriority: '无优先级',
    noWorkflowOrAuth: '当前状态无法继续流转或者没有权限',
    readonlyStatus: '只读状态，请联系管理员配置。',
    approvalStatus: '该流转需要审批完成后才能流转',
    viewWorkflow: '查看工作流图',
    deletePriority: '删除优先级',
    priorityTip: '个事项在使用，删除优先级需要选择新的选项替换它',
    priorityModalLabel: `优先级「{{name}}」共有 {{count}} 个事项在使用，删除优先级需要选择新的选项替换它`,
  },
  timeRange: {
    default: {
      separator: ['分隔符'],
      placeholderStart: '占位提示（开始）',
      placeholderEnd: '占位提示（结束）',
      font: ['至'],
      placeholder: [
        '请输入占位提示（开始），最大10个字符',
        '请输入占位提示（结束），最大10个字符',
        '请输入字段说明，最大200个字符',
      ],
    },
    FormItem: {
      format: ['时间格式', '请设置时间格式'],
      separator: ['分隔符', '请设置日期范围分隔符，长度1-2个字符'],
      label: ['占位提示（开始）', '占位提示（结束）', '字段说明'],
    },
  },
  tree: {
    default: {
      addChildren: '新建子级',
    },
    FormField: {
      multiple: '是否支持多选',
      fieldDesc: '字段说明',
      placeholder: '占位提示',
    },
  },

  user: {
    default: {
      userGroup: '用户组为',
      placeholder: ['请选择用户组'],
      currentUser: '当前用户',
    },
  },
  editor: {
    toolbar: {
      alignLeft: '左对齐',
      alignRight: '右对齐',
      alignCenter: '居中对齐',
      headerline: '标题',
      bold: '加粗',
      italic: '倾斜',
      underline: '下划线',
      bgcolor: '背景颜色',
      highlight: '文本高亮',
      strikethrough: '删除线',
      fontSize: '字号',
      lineHeight: '行高',
      color: '字色',
      orderedList: '有序列表',
      unorderedList: '无序列表',
      table: '插入表格',
      image: '插入图片',
      link: '超链接',
      code: '插入代码',
    },
    clearButtonText: '清除',
    customColorButtonText: '自定义',
    allPerson: '所有人',
    companyPerson: '企业内成员',
    possiblePerson: '可能@的人',
  },

  tag: {
    chosen: '已选择',
    items: '项',
    tag: '标签',
    placeholder: '请输入内容',
    message: {
      error: '已超过标签最大总数',
    },
    alreadyMaximum: 'Tags size is already maximum',
  },

  userGroup: {
    chooseRange: '选择范围',
    name: '用户组',
    all: '全部用户组',
    searchPlaceholder: '请输入搜索关键字',
  },
};

export const dataSource = {
  default: {
    classifyManagement: '数据源分类管理',
    management: '数据源管理',
    setting: '数据项设置',
    advancedSettings: '高级设置',
    colorPattern: '颜色模式',
    inProjectEditing: '项目内编辑',
    multilevelPresentation: '多层级展示',
    addSubmit: '确认添加',
    createDataSource: '新建数据源',
    createDataItem: '新建数据项',
    typeName: '类别',
    desc: '集中统一定制与管理业务常量数据，在这里定义的数据源可以被字段引用',
  },
  modal: {
    editDataSource: '编辑数据源',
    delete: {
      title: '删除数据源',
      content: '删除数据源「{{name}}」将影响使用该数据源的业务，您确定要删除吗？',
    },
    deleteDataSourceType: {
      title: '删除数据源分类',
      content: '删除该分类将影响使用此数据源类型的业务，您确定要删除吗？',
    },
    label: '数据项名称',
    value: '数据项值',
    parentValue: '上级数据项',
  },

  view: {
    pageHeader: {
      // 数据源管理/数据源设置
      title: '数据源管理/数据源设置',
      subTitle: '您可以在这里配置数据源数据，支持人工录入与外部数据源集成两种方式，提供数据源层级及高级数据规则设定',
      name: '数据源',
      type: global.type, // '类型',
      description: global.description, //  '描述',
      classificationManagement: '分类管理',
    },
  },
};

export default {
  fields,
  fieldBehavior,
  dataSource,
};
