// 表单语句
import date from './date';
import global from './global';

export const formField = {
  fieldValue: '字段值',
  check: '检查是否',
  selectValidateField: '请选择校验字段',
  processType: '审批流类型',
  lineKey: '节点名称（后续节点有应用到此节点的响应主体，可使用该节点名称获取）',
  relate: '相关事项',
  relateType: '关联类型',
  relateTypeMode: '链接类型',
  allRelateType: '所有关联类型',
  firstValue: '第一个值',
  condition: '关系',
  secondValue: '第二个值',
  regularExpression: '正则表达式',
  field: '字段',
  expression: '筛选条件',
  functionStr: `聚合函数（示例: return items.map(item=>item.name).join('，'), 其中items为符合条件事项列表）`,
  header: '如何在后续规则操作中访问汇聚字段的返回值？',
  to: '收件人',
  theme: '主题',
  content: '内容',
  comments: '评论',
  linkType: '事项关联类型',
  linkTypeMode: '链接类型',
  destinationSourceType: '链接事项',
  destinationStatus: '目标状态',
  postType: '通知方式',
  timeout: '超时时间(ms)',
  methods: 'HTTP 方法',
  contentType: 'Web 请求body',
  customBody: '自定义数据',
  responseEnabled: '勾选后，直到我们收到针对此Web请求的响应，才会执行后续规则的操作',
  variable: '变量名称',
  type: '相关事项的类型',
  bpmnStatus: '审批流是否通过',
  conditionsLabel: '检查以执行',
  isNeed: '监控更改的字段',
  sourceWorkspace: '源项目',
  targetWorkspace: '目标项目',
  start: '起始状态',
  end: '结束状态',
  target: '目标状态',
  anyStatus: '任意状态',
  isSearch: '运行Iql搜索',
  range: '范围',
  scenes: '自动化场景',
  parent: '分组',
  filterSource: '数据来源',
  iql: '自定义筛选条件',
  icon: ['选择图标', '图标'],
  accessType: '访问权限',
  preview: '预览',
  item: {
    includeStatus: '状态',
    tip: ['事项初始状态（复制成功后事项状态默认初始状态）', '同步事项状态（复制成功后事项状态为源事项状态）'],
    placeholder: ['请输入事项层级方案名称，2-40个字符', '请输入描述信息，最多200字'],
    text: [
      '通过左右拖拽类型区块实现添加/移除事项层级选项、上下拖拽调整层级顺序',
      '红色标注的类型代表已经被删除，请尽早替换',
    ],
  },
  key: global.key,
  filter: {
    name: global.name,
    global: {
      title: '筛选类型',
      personalFilter: {
        title: '个人筛选',
        text: '（只有你自己可以查看到这个查询）',
      },
      globalFilter: {
        title: '全局筛选',
        text: '（所有人可以查看）',
      },
    },
  },
  system: {
    dateFormat: '日期时间格式',
  },
  workspace: {
    selectWorkspace: global.select + global.workspace, // 选择空间
    hasItems: {
      label: global.workspace + global.template + global.content,
      value0: '仅项目配置',
      value1: '项目配置和事项',
    },
    name: global.workspace + global.template + global.name,
    workspaceScheme: '空间配置方案',
    description: global.description,
    workspaceAvatar: '空间头像',
    selectPermissionScheme: '选择权限方案',
    permissionScheme: '权限方案',
    workspaceKey: '空间标识',

    itemTypeScheme: global.workspace.itemTypeHierarchyScheme,
    itemTypeScreenScheme: global.workspace.itemTypeScreenScheme,
    workflowScheme: global.workspace.workflowScheme,
    securityLevelScheme: global.workspace.securityLevelScheme,

    selectIcon: '选择空间头像',
    selectMoveWorkspace: '选择迁移空间',
    createType: {
      label: '创建方式',
      BASE_WORKSPACE_TEMPLATE: '基于模板创建',
      BASE_WORKSPACE_SCHEME: '创建空白空间',
    },
    workspaceTemplate: '选择空间模板',
    templateClassifyName: '模板分类名称',
    workspaceTemplateName: '空间模板名称',
    templateCategory: '模版分类',
    cover: '模版封面图',
    boardViewType: '视图类型',
  },
  application: {
    appName: '应用名称',
    appKey: '唯一标识',
    appEnv: '应用环境',
    appVersion: '应用版本',
    appPackage: '上传文件',
    autoUpgradeTenant: '批量安装到租户',
  },
  fields: {
    dataSourceType: '数据源',
    dataCondition: '数据源条件',
    condition: '数据源条件（配置数据源获取的条件)',
    simpleDisplay: '展现形式',
    display: '展现形式（配置数据源获取的条件，例{key}、{name}。）',
    mode: '是否支持多选',
    range: '起止日期范围',
    fieldDesc: '字段说明',
    format: '日期格式',
    dateRange: '时间段',
    maxLength: '最大输入长度',
    fieldValue: '个字符',
    fieldName: '列名称',
    fieldType: '列类型',
    fieldOptions: '列选项',
    fieldTypes: '字段配置',
    addColumnButton: '新增列',
    defaultValue: '默认集合',
    component: '组件类型',
    dataType: '数据返回格式',
    maxCount: '最大上传个数',
    limitSize: '单个文件大小限制',
    ck: '文件类型',
    userAddonAfter: '自定义后缀',
    addonAfter: '文件类型后缀',
    formulaDetail: '公式详情',
    noreferrer: '使用帮助',
    hierarchicalRelationship: '层级关系',
    relateChild: '关联为子级',
    relateParent: '关联为父级',
    tagMaxinum: '标签最大总数',
    isCustomized: '支持自定义标签',
    tagMaxLength: '自定义标签字符最大长度',
    colorPriority: '优先级颜色',
    filesCount: '个文件',
    characters: '个字符',
    reIndexing: '重新索引',
    reIndexingDescription:
      '请注意，进行整型和浮点型类型切换后需要重新刷索引，否则导致数值字段显示不正确。刷索引期间将导致系统不可用，请确认无误后再进行修改数值类型。',
  },
  sprint: {
    name: '迭代名称',
    capacity: '迭代容量',
    duration: date.duration, // '持续时间',
    startTime: date.startTime, //'开始时间',
    endDate: date.endTime, // '结束时间',
    goal: '迭代目标',
  },
};

export default formField;
