/**
 * @name global 全局语句
 */

const modal = {
  addTitle: '新增',
  createTitle: '新建',
  editTitle: '编辑',
  deleteTitle: '删除',
  okText: '确认',
  cancelText: '取消',
  operateSuccess: '操作成功',
  operateFail: '操作失败',
  content: {
    areYouSure: '确定删除吗？',
    deleteTip: '删除后数据将不能恢复，请谨慎操作',
  },
};

const getCreateModule = moduleName => `${modal.createTitle}${moduleName}`;
const getEditModule = moduleName => `${modal.editTitle}${moduleName}`;
const getDeleteModule = moduleName => `${modal.deleteTitle}${moduleName}`;
// 按钮文案函数
const getBtnText = txt => `${global.newAdd}${txt}`;

export const global = {
  getBtnText,
  api: {
    put: '更新',
    patch: '更新',
    post: '创建',
    delete: '删除',
  },
  update: '更新',
  back: '返回',
  complete: '完成',
  success: '成功',
  fail: '失败',
  updatedAt: '更新于',
  editedAt: '修改于',
  running: '执行中',
  //
  save: '保存',
  saveAs: '另存为',
  modify: '修改',
  edited: '已编辑',

  cancel: '取消',
  copy: '复制',
  duplicate: '副本',
  config: '配置',
  configTitle: '配置{{name}}',
  saveSuccess: '保存成功',
  saveFail: '保存失败',
  logs: '日志',
  delete: '删除',
  pluginTitle: '插件',
  newAdd: '新建',
  create: '创建',
  add: '添加',
  edit: '编辑',
  plugin: '插件',
  name: '名称',

  setAuth: '权限',
  remove: '移除',
  total: '总数',
  user: '用户',
  userGroup: '用户组',
  userOrUserGroup: '用户/用户组',
  operation: '操作',
  batch: '批量',
  view: '查看',
  board: '面板',
  type: '类型',
  auth: '授权',
  all: '全部',
  role: '角色',
  rule: '规则',
  tip: '提示',
  deleteTip: '是否确认要删除',
  createdAt: '创建时间',
  createdBy: '创建人',
  modifyTime: '修改时间',
  permission: '权限',
  scheme: '方案',

  management: '管理',
  itemGroups: '事项组',
  permissionManagement: '权限管理',
  description: '描述',
  typeName: '分类名称',
  saveWorkspaceTemplate: '保存为空间模板',
  template: '模版',

  expandToolbar: '展开工具栏',
  collapseToolbar: '收起工具栏',

  // filter:
  filter: '筛选',
  sizer: '筛选器',
  conditions: '条件',
  clear: '清空',
  reset: '重置',
  base: '基础',
  // automation
  automation: '自动化',
  content: '内容',
  select: '选择',
  field: '字段',
  copyField: '字段复制',
  cornValue: '高级(CRON表达式)',
  //
  tag: '标签',
  uploadText: '请选择文件',
  result: '返回值',
  error: '错误',
  expression: '表达式',
  eg: '例如',
  condition: '条件',
  standard: '标准',
  process: '审批流',
  basic: '基本',
  component: '组件',
  newNode: '新增组件',
  // ---
  open: '开启',
  allOpen: '全部开启',
  close: '关闭',
  allClose: '全部关闭',
  // ---
  move: '移动',
  search: '搜索',
  launch: '启动',
  scene: '场景',
  release: '发布',
  saveAndUpdate: '保存并更新',
  haveDelete: '已删除',
  rename: '重命名',
  viewAll: '查看全部',
  createBoard: '创建面板',
  // panel: '面板',
  share: '共享',
  private: '私有',
  title: '标题',
  addView: '添加视图',
  viewManage: '视图管理',
  more: '更多',
  allItems: '全部事项',
  createItem: '新建事项',
  batchOperate: '批量操作',
  refresh: '刷新',
  collapse: '收起',
  expand: '展开',

  toolbar: '工具栏',
  public: '公开',
  NoData: '暂无数据',
  noData: '暂无{{data}}',
  export: '导出',
  custom: '自定义',
  notAvailable: '暂无',
  username: '用户名',
  nickname: '昵称',
  system: '系统',
  allCheck: '全选',
  screen: '界面',
  workflowStatus: '工作流状态',
  status: '状态',
  workflowAction: '工作流动作',
  baseCondition: {
    required: '必填',
    readonly: '只读',
    hidden: '隐藏',
  },
  NoContent: '暂无内容',
  // ---------need update
  selected: '已选',
  item: '事项',
  toggle: '切换',
  attribute: '属性',
  insert: '插入',

  email: '邮箱',
  roleName: '角色',
  draft: '草稿',
  haveRelease: '已发布',

  // 后添加
  detail: '详情',
  trigger: '触发器',
  set: '设置',
  default: '默认',
  enable: '启用',
  disable: '禁用',
  uploadBy: '上传人',
  unpublish: '下架',
  upgrade: '升级',
  uninstall: '卸载',
  disabled: '禁用',
  source: '来源',
  classify: '分类',
  yes: '是',
  not: '否',
  no: '不是',
  defaultValue: '默认值',
  data: '数据',
  subWorkspace: '所属空间',
  up: '上移',
  down: '下移',
  key: '唯一标识',
  address: '地址',
  header: '负责人',
  version: '版本',

  // file-------
  file: '文件',
  zipFile: '压缩包',
  table: '表格',
  image: '图片',
  word: 'word 文档',
  ppt: 'PPT文稿',
  excel: 'Excel表格',
  uploadFile: '文件上传',
  preview: '预览',
  prefix: '前缀',
  suffix: '后缀',
  formulaDetail: '公式详情',
  relateItem: '事项关联',
  character: '字符',
  regularExpression: '正则表达式',
  max: '最大值',
  min: '最小值',
  int: '整型',
  float: '浮点型',
  step: '步长',
  precision: '精度（小数位）',
  // -----------
  priority: '优先级',
  stateless: '无状态',
  have: '有',
  workspace: '空间',
  itemType: '类型',
  workspaces: {
    name: '空间名称',
    workspaceType: '空间类型',
    template: '空间模版',
    itemTypeHierarchyScheme: '类型层级方案',
    noItemTypeHierarchyScheme: '暂无类型层级方案',
    itemTypeScreenScheme: '类型界面方案',
    noItemTypeScreenScheme: '暂无类型界面方案',
    itemTypeWorkflowScheme: '类型工作流方案',
    itemWorkflowScheme: '事项工作流方案',
    noWorkflowScheme: '暂无工作流方案',
    workflowScheme: '工作流方案',
    securityLevelScheme: '安全级别方案',
    noSecurityLevelScheme: '暂无安全级别方案',
    permissionSchemeName: '角色权限方案',
    createScreen: '新建界面',
    editScreen: '编辑界面',
    viewScreen: '查看界面',
    workflow: '工作流',
    permissionScheme: '权限方案',
  },
  workflowScheme: '工作流方案',
  // modal 提取
  modal: {
    //...modal,
    getCreateModule,
    getEditModule,
    getDeleteModule,
  },
  columns: {
    name: '名称',
    iconAndName: '图标/名称',
    description: '描述',
    order: '排序',
    avatar: '头像',
    role: '角色',
    email: '邮箱',
    tag: '角色名称',
    type: '类型',
    username: '用户名称',
    index: '序号',
    date: '日期',
    state: '状态',
    reason: '原因',
    size: '大小',
    status: '状态',

    operation: {
      title: '操作',
      config: '配置',
      edit: '编辑',
      delete: '删除',
      rename: '重命名',
      addChild: '添加子角色',
      download: '下载',
      translate: '翻译',
    },
    forbiddenActive: '已禁用',
    start: '已启用',
    count: {
      title: '开启/关闭状态',
      enabledCount: '{{enabledCount}}个开启',
      disabledCount: '{{disabledCount}}个关闭',
    },
    isShow: '显示',
  },
  pagination: {
    totalDefault: '共 {{total}} 条数据',
    itemTotal: '共 {{total}} 个事项',
    workspaceTotal: '共 {{total}} 个空间',
    boardTotal: '共 {{total}} 个面板',
    modalTitle: '生效筛选条件为「面板筛选与视图筛选的交集」：',
  },
  // 权限相关
  permissions: {
    ForbiddenPage: '需要权限，请联系管理员',
    userNoPermission: '当前用户没有查看事项权限',
  },

  downloadList: '下载列表',
  preStep: '上一步',
  link: '链接',
  for: '对于',
  For: '针对',
  in: '于',
  confirm: '确定',
  or: '或',
  errorDetail: '错误详情',
  createView: '新建视图',
  uploadImage: '上传图片',
  reply: '回复',
  nextStep: '下一步',
  import: '导入',
  defaultScreenScheme: '默认方案',
  change: '改变',
  when: '当',
  and: '且',
  upload: '上传',
  // 校验相关
  verify: {
    space: '首位或末尾存在空格',
    nameSupport: '名称仅支持汉字、英文、数字、下划线和中划线',
    nameHead: '开头不能包含空格、必须以英文或中文开头',
    required: '{{name}}不能为空',
  },
  permissionDenied: '暂无权限',
  userTypeField: '用户类型字段',
  loading: '加载中',
  comma: '，',
  space: '',
  colon: '：',

  approve: '同意',
  reject: '拒绝',
  chosenData: '已选择 {{number}} 项',

  empty: '空',

  // 描述时间相关
  today: '今日',
  thisWeek: '本周',
  thisMonth: '本月',
};

export default global;
