/**
 * lib: 库 汉语配置文件
 */

const libs = {
  default: {
    workspace: '空间',
    board: '面板',
    permission: '权限',
    tipText: `此流程只有{{text}}可以进行操作，请联系相关人员处理`,
    flowTextTip: [
      '当前事项字段[{{field}}]应该[{{condition}}]指定条件值[{{target}}]',
      '当前事项字段[{{field}}]应该[{{condition}}]',
    ],
    conditionalValues: '指定条件值',
    currentItemField: '当前事项字段',
    should: '应该',
    SYSTEM_FIELD_MAP: {
      text: '文本',
      dropDownOption: '下拉选项',
      bindingWorkspace: '绑定空间',
      date: '日期',
      user: '用户',
    },
    CONTAINER_WIDGETS: {
      workContainer: '行容器',
      TabsContainer: '标签页',
      TabsContainerDesc: '添加一个标签页',
      CollapseContainer: '折叠面板',
      CollapseContainerDesc: '添加一个折叠面板',
      RowContainer: '单栏容器',
      RowContainerDesc: '行容器 | 形成多行单列的空白区域',
      RowContainerTwo: '双栏容器',
      RowContainerTwoDesc: '行容器 | 形成多行双列的空白区域',
      RowContainerThree: '三栏容器',
      RowContainerThreeDesc: '行容器 | 形成多行三列的空白区域',
    },
    SWITCH_COMPONENT_COMMON_LIST: {
      CONDITION_COLOR: '新建条件',
      CONDITION_COLOR_DESC: '只有当条件全部满足时才会执行操作',
      ACTION_COLOR: '新建操作',
      ACTION_COLOR_DESC: '当规则触发时，选择对系统进行更改的操作',
      BRANCH_COLOR: '新建分支',
      BRANCH_COLOR_DESC: '对这些事项的规则进行分支并运行条件和操作',
      TRIGGER: '触发器',
      TRIGGER_DESC: '选择触发此规则的事件，触发器可以监听事件或按计划运行',
    },
    AUTO_NODE_LIST: {
      TRIGGER_ITEM_CREATED: '事项创建时',
      TRIGGER_ITEM_CREATED_DESC: '当事项创建时触发此规则',
      TRIGGER_ITEM_UPDATED: '事项更新时',
      TRIGGER_ITEM_UPDATED_DESC: '当事项信息更新时触发此规则',
      TRIGGER_ITEM_DELETED: '事项删除时',
      TRIGGER_ITEM_DELETED_DESC: '当事项删除时触发此规则',
      TRIGGER_ITEM_FIELD_CHANGED: '字段值已更改',
      TRIGGER_ITEM_FIELD_CHANGED_DESC: '当事项的字段值发生变更时触发此规则',
      TRIGGER_ITEM_TRANSITIONED: '事项已转换',
      TRIGGER_ITEM_TRANSITIONED_DESC: '当事项的工作流状态发生流转时触发此规则',
      TRIGGER_SCHEDULE: '定时触发器',
      TRIGGER_SCHEDULE_DESC: '按照计划在特定时间内执行此规则',

      TRIGGER_ITEM_LINK_DELETED: '已删除事项关联',
      TRIGGER_ITEM_LINK_DELETED_DESC: '当一个事项解除与另一个事项的关联时，触发此规则',
      TRIGGER_ITEM_LINK_CREATED: '事项已关联',
      TRIGGER_ITEM_LINK_CREATED_DESC: '当一个事项关联到另一个事项时触发此规则',
      TRIGGER_BPMN_TRANSITIONED: 'Bpmn审批流程流转时',
      TRIGGER_BPMN_TRANSITIONED_DESC: '当Bpmn审批流程发生流转时触发此规则。',
      TRIGGER_BPMN_FINISHED: 'Bpmn审批流程结束时',
      TRIGGER_BPMN_FINISHED_DESC: '当Bpmn审批流程结束时触发此规则。',
      TRIGGER_WORKSPACE_CREATED: '空间创建时',
      TRIGGER_WORKSPACE_CREATED_DESC: '当空间创建时触发此规则',
      CONDITION_IF_FIELDS: '事项字段条件',
      CONDITION_IF_FIELDS_DESC: '检查事项的字段是否满足某个条件',
      CONDITION_ITEM_USER: '用户条件',
      CONDITION_ITEM_USER_DESC: '检查用户类型字段是否满足某个条件',
      CONDITION_BPMN_CONDITION: 'Bpmn审批流条件',
      CONDITION_BPMN_CONDITION_DESC: 'Bpmn审批流条件。',
      CONDITION_ITEM_RELATE: '相关事项条件',
      CONDITION_ITEM_RELATE_DESC: '检查是否存在符合条件的相关事项',
      CONDITION_IF_APPROVAl: '工作流审批条件',
      CONDITION_IF_APPROVAl_DESC: '检查事项工作流审批条件是否满足',
      CONDITION_EXPRESSION: '高级比较条件',
      CONDITION_EXPRESSION_DESC: '使用表达式或正则表达式比较两个基础类型的值。',
      ACTION_ITEM_DELETE: '删除事项',
      ACTION_ITEM_CREATE: '创建事项',
      ACTION_ITEM_CREATE_DESC: '给某个项目创建个新的事项',
      ACTION_SUB_ITEM_CREATE: '创建子事项',
      ACTION_SUB_ITEM_CREATE_DESC: '给某个事项创建1个或多个子事项',
      ACTION_BPMN_CREATE: '创建审批流',
      ACTION_BPMN_CREATE_DESC: '给某个事项创建审批流程',
      ACTION_ITEM_CLONE: '克隆事项',
      ACTION_ITEM_CLONE_DESC: '将复制此事项到指定项目中',
      ACTION_ITEM_EDIT: '编辑事项',
      ACTION_ITEM_EDIT_DESC: '修改事项的某些字段值',
      ACTION_ITEM_TRANSITION: '转换事项',
      ACTION_ITEM_TRANSITION_DESC: '将事项的状态转换为特定状态',
      ACTION_EMAIL_SEND: '发送电子邮件',
      ACTION_EMAIL_SEND_DESC: '向指定地址发送电子邮件',
      ACTION_NOTIFICATION_SEND: '发送通知消息',
      ACTION_NOTIFICATION_SEND_DESC: '向指定的对象发送通知消息',
      BRANCH_ITEM: '分支规则/相关事项',
      BRANCH_ADVANCED_ITEM: '高级分支',
      BRANCH_ADVANCED_ITEM_DESC: '对事项表达式执行操作和条件',
      CONDITION_IF: '使用“if”、“else-if”和“else”执行不同的操作以控制流程。',
      CONDITION_ELSE:
        '如果前面的“if/else-if”块无法满足其条件，则“else”块将执行该块内的操作。“else”块可以包含自己的条件，使其成为“else-if条件”，或者如果它是最后一个“else”块，可以将其留空。',
      CONDITION_ELSE_IF:
        '如果前面的“if/else-if”块无法满足其条件，则“else”块将执行该块内的操作。“else”块可以包含自己的条件，使其成为“else-if条件”，或者如果它是最后一个“else”块，可以将其留空。',
      ACTION_WEB_REQUEST: '发送Web请求',
      ACTION_WEB_REQUEST_DESC: '将请求发送到给到的URL',
      ACTION_ITEM_LINK: '事项链接',
      ACTION_ITEM_LINK_DESC: '创建当前事项与指定事项之间的关联',
      ACTION_ITEM_LINK_DELETE: '删除事项链接',
      ACTION_ITEM_LINK_DELETE_DESC: '删除当前事项与指定事项之间的关联',
      ACTION_COLLECT_ITEM: '相关事项字段汇聚',
      ACTION_COLLECT_ITEM_DESC: '将相关事项字段信息汇聚到其他事项',
    },
    AUTOMATION_SIDE_BAR_DETAILS: {
      TRIGGER_ITEM_UPDATED: '规则在事项更新时执行',
      TRIGGER_ITEM_CREATED: '规则在事项创建时执行',
      TRIGGER_ITEM_DELETED: '规则在事项删除时执行',
    },
  },
  apis: {
    securityLevel: {
      deleteSecurityLevel: {
        noExistForSecurityField: '安全字段已不存在',
        deleteFail: '删除失败',
      },
    },
  },
  app: {
    moreAction: '更多操作',
  },
  dicts: {
    modulesMapping: {
      itemAction: '事项动作',
      itemPanel: '事项面板',
      itemActivity: '事项活动',
      adminPage: '设置页面',
      appPage: '应用页面',
      workspacePage: '空间页面',
      trigger: '触发器',
      function: '云函数',
      webtrigger: '接口定义',
      viewAction: '视图操作',
      customFieldType: '自定义字段类型',
      customField: '自定义字段',
      importer: '钩子:事项导入',
      beforeCreateOrUpdateModal: '事项创建/编辑弹窗接入点（字段编辑区域上方）',
      afterCreateOrUpdateModal: '事项创建/编辑弹窗接入点（字段编辑区域下方）',
      customItemType: '自定义类型',
      chart: '工作台图表',
      automation: '自动化',
    },
  },
  error: {
    default: {
      reLogin: '请重新登录',
      errorData: '请求失败',
    },
    MsgSet: {
      'Object not found for delete.': '该数据已被删除，请刷新页面',
      'Object not found.': '该数据不存在，请刷新页面',
      'Invalid username/password.': '用户名或密码错误',
      'Account already exists for this username.': '此用户名的帐户已存在',
      'Account already exists for this email address.': '此电子邮件地址的帐户已存在',
    },
  },
  global: {
    CHART_OPTION_UNSAVE: '您有未保存的图表参数配置，请确认是否保存后再退出？',
    COMPUTES: {
      count: '事项数',
      sum: '求和',
      avg: '平均数',
      max: '最大值',
      min: '最小值',
    },
    NAME_LENGTH_ERROR: `名称，长度{{min}}-{{max}}个字符`,
    NAME_VALIDATE_ERROR: '名称必须以字母或汉字开头',
  },
  iql: {
    count: '事项数',
    order: '排序',
    toIqlNameTitle: '标题',
    toIqlNameItemId: 'key',
  },
  message: {
    default: {
      success: '成功',
      create: '创建',
      patch: '更新',
      delete: '删除',
    },
  },
  regExp: {
    nameTest: '开头不能包含空格、必须以英文或中文开头',
  },
  usePluginManifest: {
    default: {
      delete: '（已删除）',
      forbidden: '（已禁用）',
    },
    getErrorText: {
      timeout: '应用加载超时',
      error: '应用加载失败',
    },
  },
  withPageLayout: {
    ForbiddenPage: {
      title: '当前用户没有管理权限',
    },
  },
  withPermission: {
    title: `当前用户没有{{view}}权限`,
  },
  workflow: {
    user: '用户',
    role: '角色',
    group: '用户组',
    userFields: '用户字段',
    workspaceRoles: '空间角色',

    yes: '是',
    no: '不是',

    equalTo: '等于',
    notEqualTo: '不等于',

    lessThan: '小于',
    greaterThan: '大于',

    lessThanOrEqualTo: '小于等于',
    greaterThanOrEqualTo: '大于等于',

    containedIn: '包含',
    notContainedIn: '不包含',

    null: '为空',
    notNull: '不为空',
    belongTo: '属于',
    notBelongTo: '不属于',

    BeganIn: '开始于',
    EndIn: '结束于',
    notEmpty: '非空',
    regular: '正则',
    regex: '包含正则表达式',
    regexMatchAll: '与正则表达式完全匹配',
    regexNotMatch: '与正则表达式不匹配',
    AsEarlyAs: '早于',
    LaterThan: '晚于',
    between: '介于',
    anyContain: '包含任意',
    allContain: '包含所有',
    allDoesNotContain: '均不包含',
    oneOfThem: '是其中之一',
    notOneOfThem: '不属于其中之一',

    addCom: '新增组件',
    currentItem: '当前事项',
    ruleBranch: '对此规则进行分支，并对当前事务进行后续条件和操作',
    queryParentItem: '(查找触发此规则的事项的父事项)',
    queryChildItem: '(查找触发此规则的事项的子事项)',
    queryAllRelateItem: '(查找触发此规则的事项的所有关联事项)',
    queryDataQuoteItems: '(查找触发此规则的事项的数据引用字段)',
    parentItem: '父事项',
    childItem: '子事项',
    relateItem: '关联事项',
    triggerItem: '触发器事项',
    expression: '使用表达式指定',
    expressionDesc:
      '使用表达式指定关联事项的 objectId，例如：#{triggerNode.body.destination.objectId}# -触发器事项的关联事项',
    iql: '使用iql查询结果',
    iqlDesc: '如果事项较多时会影响性能，最多支持 {{max}} 个事项',
    dataQuote: '数据引用',

    createItem: '创建事项',
    editItem: '编辑事项',
    conversionItems: '转换事项',
    triggerProject: '触发器项目',
    sameProject: '同一项目',
    triggerItemType: '触发器类型',
    sameProjectItem: '同一类型',
    released: '已发布',
    unreleased: '未发布',
    archived: '已归档',
    approvaled: '审批通过',
    noApprovaled: '审批不通过',
    anyProject: '任意项目',
    fromCurrentItem: '来自当前事项',
    formTrggierItem: '来自触发器事项',
    formParentItem: '来自父事项',
    allMatch: '全部匹配',
    partMatch: '部分匹配',
    triggeredUser: '触发事件的用户',
    allWorkspace: '全部空间',
    multipleWorkspace: '多个空间',
    firstDayMouth: '每月第一天',
    lastDayMouth: '每月最后一天',
    first: '第一个',
    last: '最后一个',
    Date: '日期',
    date: {
      second: '秒',
      seconds: '秒',
      minute: '分钟',
      minutes: '分钟',
      hour: '小时',
      hours: '小时',
      day: '天',
      days: '天',
      week: '周',
      mouth: '月',

      Sunday: '周日',
      Monday: '周一',
      Tuesday: '周二',
      Wednesday: '周三',
      Thursday: '周四',
      Friday: '周五',
      Saturday: '周六',
    },
    SUPER_ADMIN_ROLE_NAME: '超级管理员',
    ADMIN_ROLE_NAME: '企业管理员',
    Member: '成员',

    itemData: '事项数据',
    customData: '自定义数据',
    itemType: '类型',

    createTime: '创建时间',
    itemCount: '事项数',

    itemTypeDistribution: '类型分布',
    multidimensionalTable: '多维表格',
    itemBurnoutChart: '事项燃尽图',
    personLoadRanking: '人员负载排名',
    leader: '负责人',
  },
};

export default libs;
