// 提示语句
export const message = {
  default: {
    submitSuccess: '提交成功',
    uploadLoading: '上传中',
    systemNameError: '请选择系统内请求',
    urlError: 'URL不能为空',
    no: '暂无',
    mergeSuccess: '合并成功',
    deleteSuccess: '删除成功',
    deleteFail: '删除失败',
    addSuccess: '添加成功',
    editSuccess: '编辑成功',
    updateSuccess: '更新成功',
    createSuccess: '创建成功',
    emptyDescription: '暂无描述',
    valueError: '值不能为空',
    contentError: ['内容不能为空', '内容字数不能超过10000'],
    variableError: ['变量名称不能为空', '变量名称仅支持英文字符'],
    executiveStandard: '执行标准不能为空',
    moveSuccess: '移动成功',
    noData: '暂无数据',
    saveSuccess: '保存成功',
    create: '新建成功',
    newAddSuccess: '新增成功',
    COMMON_ERROR_MESSAGE: '操作异常，请稍后重试',
    modifySuccess: '修改成功',
    modifyFail: '修改失败',
    upload: {
      success: '上传成功',
      fail: '上传失败',
    },
    install: {
      success: '安装成功',
      fail: '安装失败',
    },
    download: {
      fail: '下载失败',
      downloading: '文件下载中...',
    },
    delete: {
      error: '删除失败',
      success: '删除成功',
      tips: '删除后数据将不能恢复，请谨慎操作',
      confirm: '确定删除「{{name}}」吗？',
      typeConfirm: type => `确定删除${type}「{{name}}」吗？`,
    },
  },
  workspace: {
    sourceWorkspaceError: '源项目不能为空',
    targetWorkspaceError: '目标项目不能为空',
    itemMoveSuccess: '事项迁移成功',
    delWorkspaceRole: '删除空间角色成功',
    permissionScheme: '请选择权限方案',
    itemTypeScheme: '请选择类型层级方案',
    itemTypeScreenScheme: '请选择类型界面方案',
    workflowScheme: ['请选择事项工作流方案', '请选择工作流方案'],
    selectWorkspaceTemplate: '请选择空间模板',
    cover: '请选择封面图',
    selectWorkspace: '请选择空间',
    inputWorkspaceTemplateName: '请输入空间模版名称',
    selectWorkspaceConfigScheme: '请选择空间配置方案',
    selectMoveWorkspace: '请选择迁移空间',
    keyLength: '唯一标识, 长度 2-40 个字符',
    errorRules: '格式不正确，仅支持字母、数字、下划线且必须以字母开头',
    exists: '当前唯一标识已存在',
    boardExistInGroup: '分组中还存在面板',
    lastBoard: '已经是最后一个面板了',
    selectDelete: '请选择删除操作',
    selectMoveBoard: '请选择移动面板',
  },
  filters: {
    conditions: ['最多只能有10个筛选项', '最多只能有20个筛选项'],
    newFilters: '选择的筛选字段已存在，不能切换',
    screeningField: '请选择筛选字段',
    selectCondition: '请选择条件',
    addFilterText: '添加条件',
    inputNumber: '请输入数字',
    conditionsTooLong: '查询条件过长，请删减后重试',
  },
  item: {
    getItem: '事项获取中，请稍等',
    copyItemError: '复制事项错误',
    noItemType: '空间无可用类型，请检查空间事项层级方案',
    screenConfigError: '界面配置获取异常，请检查后重试',
    selectItemRelate: '请选择事项关联关系',
    linkTypeError: ['事项关联类型不能为空', '链接事项不能为空'],
    expressionError: '表达式不能为空',
    relateError: '相关事项不能为空',
    requiredChild: '必须新建一个子事项',
  },
  automation: {
    noEmptyName: '自动化名称不能为空',
    automationDesc: '场景描述不能超过300字',
    sceneTip: '修改失败，该场景已被删除',
    // 自动化场景
    automationDeleteError: '请选择删除后的操作',
    getNotificationError: '获取消息通知类型失败',
    getAutomationRunningLogsError: '获取运行日志失败',
    moveScenes: '请选择要移动到的自动化场景',
  },
  users: {
    tips: {
      name: '请输入名称',
      existed: '场景名称已存在',
    },
    hasSameNameError: '存在同名分组',
    groupAll: '全部分组',
  },
  views: {
    config: '请配置完成占比字段',
    startTimeRange: '开始时间范围错误',
    entTimeRange: '结束时间范围错误',
    cancelRelateSuccess: '关联关系解除成功',
    addRelateFailed: '事项关联失败，{{reason}}',
    addRelateSuccess: '关联关系添加成功',
    removeItemSuccess: '事项删除成功',
  },
  application: {
    success: '设置成功',
    error: '设置空间方案出错了',
    uninstallError: '卸载失败',
    unpublishError: '下架失败',
    unpublishSuccess: '下架成功',
    uninstallSuccess: '卸载成功',
    uploadSuccess: '上传成功',
    setWorkspaceError: '设置空间出错了',
  },
  fields: {
    typeError: '相关类型不能为空',
    valueNullError: '字段值不能为空',
    keyError: '字段来源不能为空',
    expressionError: ['字段条件不能为空', '表达式不能为空'],
    fieldKeyError: '字段不能为空',
    isNeedError: '该字段不能为空',
    aimError: '操作字段不能为空',
    OBJECT_NOT_FOUND: '该字段行为不存在',
    lessThan: '{{file}}大小不能超过{{maximumFileSize}}MB',
    uploadFileError: '文件上传失败，请检查网络并稍后重试',
    removeFileError: '文件删除失败，请检查网络并稍后重试',
    uploadAnnexError: '附件上传失败，请检查网络并稍后重试',
    removeAnnexError: '附件删除失败，请检查网络并稍后重试',
    maxTenOption: '最多只能有{{count}}个筛选项',
    selectOptionExist: '选择的筛选字段已存在，不能切换',
    noDataRefresh: '暂无数据或事项已删除,请刷新后重试',
    noModifyDate: '日期类型确定后不能修改',
    columnNameRepeat: '列名称重复，请重新输入',
    selectDeleteDataColumn: '请选择要删除的数据行',
    selectMoveDataColumn: '请选择要移动的数据行',
    noBlankForName: '名称输入不能为空格',
    noBlankForKey: '唯一标识输入不能为空格',
    exist: '填写的值已存在',
    noBlankForComponent: '组件输入不能为空格',
    uploadFile: {
      type: '当前上传文件只支持{{addonAfter}}格式',
      empty: '不能上传空文件',
      limitSize: '{{file}} 大小不能超过 {{maximumFileSize}}MB',
      maxCount: '最多上传{{maxCount}}个文件',
    },
    bindingOneParent: '只能绑定一个父级',
    noThisParent: '不能选择当前事项为父级',
    addParentItem: '成功添加父级别事项',
    noThisChild: '不能选择当前事项为子级',
    addChildItem: '成功添加子级别事项',
    removeHierarchySuccess: '解除层级关系成功',
    selectItem: '请选择事项',
    addRelateSuccess: '关联关系添加成功',
    selectItemType: '请选择类型',
    selectRelateItem: '请选择事项关联',
    selectRelateWorkItem: '请选择待关联的工作项',
    errorRequired: '错误提示必填',
    errorTip: '错误提示',
    noRangeValue: '输入的值不是设置范围内，请重新输入',
    stateFlowSuccess: '状态流转成功',
    stateFlowFailure: '状态流转失败{{messageText}}',
    noDelete: '该数据已被使用，不允许删除',
    exceededNum: '已超过标签最大总数',
    inputTag: '请输入标签名',
    noRepeatTag: '标签名不能重复',
    noRangeTime: '选择的时间不在设定范围内',
    selectPriority: '请选择优先级',
    priorityName: '优先级名称, 长度 {{MIN_LENGTH}} - {{MAX_LENGTH}}个字符',
    haveDelete: '字段已删除，不能配置',
    relateTypeModeError: '请选择链接类型',
    relateTypeError: '请选择关联类型',
    dataQuoteError: '请选择数据类型字段',
    jsonStringWarning: '输入的数据不是JSON字符串',
    firstValue: '请输入第一个值',
    secondValue: '请输入{{message}}',
  },
  sprint: {
    fail: '迭代{{text}}失败，当前用户没有操作事项的权限',
  },
  roles: {
    selectSuperiorRole: '请选择上级角色',
  },
  save: {
    error: '保存失败, 请重试',
  },
  copy: {
    success: '复制成功',
    error: '复制失败',
  },
  order: {
    success: '顺序调整成功',
  },
  waring: {
    tip: '未知操作',
  },

  upload: {
    error: '上传失败',
  },
  cron: {
    noMatch: '暂不支持',
    invalidate: '表达式不合法',
    lastDay: '最后一天',
  },

  email: {
    toError: ['收件人缺少必填内容', '用户字段缺少必填字段'],
  },
  theme: {
    themeError: ['主题不能为空', '主题字数不能超过100'],
  },
  comments: {
    commentsError: '评论内容不能为空',
  },
  time: {
    timeoutError: '超时时间不能为空',
    weekError: '星期字段不能为空',
    dateError: ['日期不能为空', '时间字段不能为空'],
  },
  custom: {
    customBodyError: '自定义数据不能为空',
  },
  condition: {
    conditionError: ['条件不能为空', '值不能为空'],
  },
  bpmn: {
    bpmnStatusError: ['审批流条件不能为空', '审批流条件节点要求trigger节点需要是Bpmn的触发节点'],
  },
  board: {
    defaultBoardPermission: '默认面板权限',
  },
  IQL: {
    iqlError: '筛选条件为必填项',
  },
  filter: {
    tip: '请选择筛选器',
  },
  permission: {
    nocategory: '请选择权限类型',
    share: '请添加权限角色',
  },
  chat: {
    name: '请输入报表名称',
    alreadyExist: '当前名称已存在',
  },
};

export default message;
