export const placeholder = {
  default: {
    selectRole: '请选择角色',
    nameType: '名称（例如: Content-Type）',
    bodyNameType: '名称',
    valueType: '值（例如: application/json）',
    bodyValueType: '值',
    select: '请选择',
    selectTime: '选择时间',
    selectUserField: '请选择用户字段',
    pass: '是否通过',
    custom: '请输入自定义数据',
    expressionEg: '请输入表达式, 例如 #{item.name}#',
    selectMethods: '选择Methods',
    condition: '请选择条件',
    types: '请选择类型',
    keywords: '请输入关键字',
    enter: '按下Enter搜索',
    copy: '请选择复制来源',
    email: '请输入邮件内容, 您可以在内容中包含HTML标签',
    description: '请输入描述信息',
    enableMessage: ['启用成功', '关闭成功'],
    inputNameLength: `请输入名称，长度{{min}}-{{max}}个字符`,
    inputLink: '请输入链接',
    inputUrl: '请输入URL',
    inputDesc: '请输入描述信息，最大200字',
    input: '请输入',
    inputName: '请输入名称',
    nameExist: '当前名称已存在',
    keywordsOrItemID: '请输入标题关键字/Key',
    selectFile: '请选择文件',
    expressionForIQL: '表达式结构',
    expressionForCron: '请输入Cron表达式',
    inputTheme: '请输入主题',
    selectApprovalFlow: '选择审批流',
    selectSuperior: '请选择上级',
    enterExpression: '请填写表达式',
    selectSystemRequest: '选择系统请求',
    inputTimeout: '请输入超时时间',
    selectExecutor: '请选择执行人',
    selectRange: '请选择范围',
    search: '请输入关键字',
  },
  workspace: {
    selectBelongsToWorkspace: '请选择所属空间',
    select: '请选择',
    workspaceTemplate: '请输入空间模板名称',
    configScheme: '请选择空间配置方案',

    workspaceScheme: '空间配置方案',
    nameLength: `名称，长度{{min}}-{{max}}个字符`,
    workspaceNameLength: `请输入空间名称，长度{{min}}-{{max}}个字符`,
    workspaceKey: {
      content: '请输入空间唯一标识',
      exist: '当前唯一标识已存在',
      orContent: '请输入空间唯一标识，支持字母、数字、下划线的组合，长度{{min}}-{{max}}个字符',
    },
    selectPermissionScheme: '请选择权限方案',
    selectWorkspace: '请选择空间',
    selectTemplateCategory: '请选择模版分类',
    searchWorkspaceName: '根据空间名称进行搜索',
    workspaceName: '请输入空间名称',
    inputKey: '请输入唯一标识',
    boardViewName: `请输入视图名称，长度{{min}}-{{max}}个字符`,
    boardViewType: '请选择视图类型',
    selectBoard: '请选择面板',
    boardRule: `请输入标识，支持字母、数字、下划线、中划线的组合，长度 {{min}}-{{max}} 个字符`,
    selectGroup: '请选择分组',
  },
  // 新
  filters: {
    selectCondition: '选择条件',
    titleKeywords: '请输入标题关键字',
    expression: 'IQL表达式',
  },
  item: {
    select: '选择事项操作',
    relationItem: '请选择相关事项',
    selectRelation: '请选择关联关系',
    all: '所有关联类型',
    itemLink: '请选择链接事项',
    itemType: '请选择关联的类型',
    selectItemTitle: '请输入事项标题',
    inputItemRelate: `请输入事项关联名称，长度{{min}}-{{max}}个字符`,
    // 2-60
    inputDes: `请输入关联方描述，长度{{min}}-{{max}}个字符。`,
    selectItemType: '请选择类型',
    // 2-60
    outward: [`被关联方描述, 长度{{min}}-{{max}}个字符`],
  },
  automation: {
    name: '为您的自动化命名',
    automationRules: '请输入自动化规则名称',
    desc: '请输入描述，长度不超过 300 个字符',
    moveScenes: '请选择要移动到的自动化场景',
  },
  fields: {
    setMaxRows: '请设置最大行数',
    select: '选择字段',
    pleaseSelect: '请选择字段',
    input: '请输入字段值',
    field: '请输入字段',
    inputMaxLength: '请输入最大输入长度',
    searchContent: '搜索内容',
    fieldRepeat: '字段重复， 请重新选择',
    fieldBehaviorNameLength: `请输入字段行为名称，长度{{min}}-{{max}}个字符`,
    inputComments: '在此输入评论内容',
    placeholderTip: '占位提示',
    maxPlaceholderTip: `请输入占位提示，最大40个字符`,
    fieldDoc: '字段说明',
    maxFieldDoc: '请输入字段说明，最大200个字符',
    optionValue: '请输入选项值, 最大500个字符',
    selectDateType: '请选择日期类型',
    placeholderStart: '请输入占位提示（开始），最大10个字符',
    placeholderEnd: '请输入占位提示（结束），最大10个字符',
    selectDateFormat: '请设置日期格式',
    setDateRangeSeparator: '请设置日期范围分隔符，长度1-2个字符',
    // 1-40
    optionName: `请输入选项名名称, 长度{{min}}-{{max}}个字符`,
    inputTypeName: '请输入类型的名称',
    fieldName: `请输入字段名称, 长度{{min}}-{{max}}个字符`,
    fieldKey: `请输入字段唯一标识, 支持字母、数字、下划线的组合，长度{{min}}-{{max}}个字符`,
    uploadMaxCount: '请输入最大上传个数（默认无限制）',
    fileSize: '请输入文件大小限制（默认{{maximumFileSize}}MB)',
    customAfter: '请输入自定义后缀，多个后缀之间以逗号隔开',
    fileAfter: '文件类型后缀，不设置后缀则可以上传任意类型文件',
    prefix: '请输入前缀，最大10个字符',
    suffix: '请输入后缀，最大10个字符',
    inputItemId: '请输入完整Key进行筛选',
    inputKeywords: '请输入标题关键字或Key搜索',
    linkCards: '请选择待关联的工作项',
    inputDefaultValue: '请输入字段默认值',
    setCharacterCount: '请设置最大可输入字符数，最大1000',
    setMinRow: '请设置最小行数',
    inputReg: '请输入正则表达式',
    inputErrorTip: '请输入错误提示',
    inputMin: '请输入最小值，最大9位数字',
    inputMax: '请输入最大值，最大9位数字',
    inputPrefix: '请输入前缀，最大10个字符',
    inputSuffix: '请输入后缀，最大10个字符',
    inputStep: '请输入增长步长',
    setDecimalProgress: '请设置小数位进度',
    selectStatusType: '请选择状态类型',
    searchOrCreateTag: '输入搜索或者创建标签',
    inputSearch: '输入搜索',
    inputSearchContent: '请输入搜索的内容',
    inputMaxForSixteen: '请输入最大值，最大值为16',
    setTimeFormat: '请设置时间格式',
    selectPriority: '请选择优先级',
    inputPriorityName: '请输入优先级名称，长度 {{MIN_LENGTH}}-{{MAX_LENGTH}} 个字符',
    inputDescription: '请输入描述',
    firstValue: '可输入带有表达式的值',
  },
  sprint: {
    selectSprint: '请选择迭代',
    selectedCount: '已选择{{count}}个迭代',
    selectedCounts: '已选择{{count}}个迭代',
  },
  agileBoard: {
    empty: '暂无面板',
  },
  dataSource: {
    // 1-40
    inputName: `请输入名称，长度{{min}}-{{max}}个字符`,
    inputDataItemValue: '请输入数据项值，最大40字',
    inputNameLong: `请输入名称，长度{{min}}-{{max}}个字符`,
  },
  users: {
    userGroup: '请选择用户组',
    enterName: '请填写名称',
    nameSearch: '请输入名称搜索',
    selectUserRole: '请选择用户角色',
  },
  status: {
    target: '目标状态',
    open: '请选择开启状态',
    all: '留空将匹配所有状态',
  },
  application: {
    enterApplicationName: '请填写应用名称',
    enterKey: '请填写唯一标识',
    enterApplicationVersion: '请填写应用版本',
  },
};

export default placeholder;
