const getRequired = name => `${name}不能为空`;
const getExists = name => `${name}已存在`;
const getMin = name => `${name}最少{{min}}个字符`;
const getMax = name => `${name}最多为{{max}}个字符`;

// 校验语句
export const validate = {
  getRequired,
  getExists,
  getMin,
  getMax,
  name: {
    starts: '名称必须以字母或汉字开头',
  },
  addKey: '请输入Key',
  noRepeatKey: ['不允许重复的Key', '唯一标识不允许重复'],
  noChineseKey: 'key不允许中文',
  enterValue: '请输入Value',
  enterIQL: '请输入IQL表达式',
  approvalFlowTypeCannotBeEmpty: '审批流类型不能为空',
  nameRequired: '名称必填',
  nameNoRepeat: '名称不允许重复',
  keyRequired: '唯一标识为必填',
  keyRule: '格式不正确（小写字母开头，小写字母、数字或下划线组成）',
  version: '版本必填',
  package: '请选择应用包',
  valueNull: '字段值不能为空',
  fieldConfig: ['请选择字段', '请选择条件'],
  userValue: '用户字段不能为空',
  haveExistedName: ['名称已存在', '当前名称已存在'],
  // 2-30
  nameLength: `名称, 长度{{min}}-{{max}}个字符`,
  limitLength: '名称, 长度 {{min_length}}-{{max_length}} 个字符',
  ValidateKey: {
    keyLength: '唯一标识, 长度{{min}}-{{max}}个字符',
    keyExist: '当前标识已存在',
    keyContent: '唯一标识必须由字母数字字符 - 或 _ 组成。',
    keyRule: '格式不正确，仅支持字母、数字、下划线、中划线且数字或字母开头',
  },
  permissionView: '请选择视图权限',
  permissionViewType: '请选择视图类型',
  uploadFail: '上传失败',
  required: {
    name: '名称不能为空',
    key: '请输入唯一标识',
    tip1: '格式不正确，仅支持字母、数字、下划线且必须以字母开头',
    defaultScreenScheme: '请选择默认方案',
  },
  keyExist: '当前唯一标识已存在',
  item: {
    font: ['必填', '以下隐藏字段为必填项', '继续创建下一个', '只看必填项'],
    itemRelate: '事项关联关系',
    hierarchyLimit: '请编排层级限制',
    itemRelateNameExist: '当前事项关联名称已存在',
    // 2-60
    inward: {
      desc: '关联方描述, 长度{{min}}-{{max}}个字符',
      exist: '当前名称已存在',
    },
    type: '请选择事项关联类型',
    name: '请输入事项关联名称',
    inwardDesc: '请输入关联方描述',
    outward: '请输入被关联方描述',
    inwardItemTypeMappings: '请选择类型',
  },
  screen: {
    name: '界面方案名称不能为空',
    defaultScreen: '请选择默认方案',
    required: '名称不能为空',
    minLength: '名称最少{{length}}个字符',
    maxLength: '名称最多为{{length}}个字符',
    descLength: '描述最多支持{{length}}个字符',
  },
  fields: {
    selectConditionField: '请选择条件字段',
    selectConditionOwnership: '请选择条件所属关系',
    selectConditionContent: '请选择条件内容',
    NAME_VALIDATE_ERROR: '名称必须以字母或汉字开头',
    fieldBehaviorName: '字段行为名称不能为空',
    fieldBehaviorExist: '当前字段行为名称已存在',
    NAME_LENGTH_ERROR: '名称，长度{{min}}-{{max}}个字符',
    blankError: '格式不正确，开头和结尾不能包括空格',
    inputOptionName: '请输入选项名',
    optionNameExist: '当前选项名已存在',
    inputOptionValue: '请输入选项值',
    optionValueExist: '当前选项值已存在',
    selectColumnType: '请选择列类型',
    addOneColumn: '请至少添加一列',
    required: {
      name: '请输入名称',
      key: '请输入唯一标识',
      component: '请输入组件',
      dataReturnFormat: '请选择数据返回格式',
      expression: '请输入正则表达式',
      message: '请输入错误提示',
    },
    levelType: '请选择层级关系',
    selectedRowKeys: '请选择事项',
    checkParent: '父级事项中包含当前事项，请检查重试',
    inconformityHierarchy: '{{name}} 不符合空间层级规则，请重新选择关联',
    notChangeHierarchy: '已有父事项，无法更改层级',
    maxGreaterThanMin: '最大值不能小于最小值',
    mixLessThanMax: '最小值不能大于最大值',
    selectColor: '请选择颜色',
    viewManage: '请至少保留一个开启的视图',
  },
  dataSource: {
    noEmptyForDataItem: '数据项不能为空',
    existForOptionName: '当前选项名已存在',
    noEmptyForDataItemValue: '数据项值不能为空',
    inputCategoryName: '请输入分类名称',
    // 2-30
    categoryName: `分类名称, 长度{{min}}-{{max}}个字符`,
    noRepeatCategoryName: '分类名称不能重复',
    optionValueExist: '当前选项名值已存在',
    noRepeatDataSourceName: '数据源名称不能为空',
    dataSourceName: `数据源名称, 长度{{min}}-{{max}}个字符`,
    noEmptyForDataSourceType: '数据源类型不能为空',
  },
  workspace: {
    templateTypeName: '请输入模板分类名称',
    workspaceTemplate: '请输入空间模板名称',
    groupExist: '分组已存在',
    noEmptyforName: '名称输入不能为空',
  },
  sprint: {
    noEmptyForSprintName: '迭代名称不能为空',
    sprintName: '迭代名称最多填写{{count}}个字符',
    sprintNameExist: '迭代名称已存在',
    endTimeCannotBeEarlierThanStartTime: '结束时间不能早于开始时间',
  },
  filter: {
    name: '名称不能为空',
    global: '筛选类型不能为空',
  },
  system: {
    dateFormat: '日期时间格式必填',
  },
  user: {
    role: '用户角色不能为空',
  },
  modal: {
    hiddenRequired: `以下隐藏字段为必填项，请联系相关人员填写: {{name}}`,
    required: '{{name}}必填',
    typeError: '{{name}}输入类型错误',
    enterError: '输入错误',
    scriptError: '校验脚本错误',
  },
  screenEditor: {
    improveInfo: '组件标题未填写，请完善',
    tabName: '请完善标签页标题',
    collapseName: '请完善标题',
  },
};

export default validate;
