/**
 * Created by zhongqianxing on 2022-06-24
 */
const version = {
  versionPage: {
    pageTitle: '{{moduleName}}',
    search: '请输入搜索内容',
    create: '新建{{moduleName}}',
    versionStatus: '{{moduleName}}状态',
    tableColumnsSettings: '表格显示设置',
    table: {
      name: '{{moduleName}}',
      status: '状态',
      progress: '进度',
      startDate: '开始日期',
      releaseDate: '发布日期',
      description: '描述',
      operation: '操作',
      release: '发布',
      unRelease: '取消发布',
      archived: '归档',
      unarchive: '取消归档',
      merge: '合并',
      edit: '编辑',
      delete: '删除',
    },
    unreleased: '未发布',
    released: '已发布',
    archived: '已归档',
    start: '{{count}} 个未开始',
    inProgress: '{{count}} 个进行中',
    finished: '{{count}} 个已完成',
    fail: '{{moduleName}}{{text}}失败，当前用户没有操作事项的权限',
  },
  versionDetail: {
    delay: '已逾期 {{days}} 天',
    delays: '已逾期 {{days}} 天',
    table: {
      name: '标题',
      itemType: '类型',
      status: '状态',
    },
    navigator: '在筛选器中查看',
    all: '全部',
  },
  addVersionModal: {
    name: '{{moduleName}}名称',
    range: '时间范围',
    description: '描述',
    placeholder: ['开始时间', '发布时间'],
    nameRequired: '{{moduleName}}名称不能为空',
    nameAlreadyExists: '{{moduleName}}名称已存在',
    nameTooLong: '{{moduleName}}名称最多填写{{count}}个字符',
    rangeRequired: '时间范围不能为空',
    edit: '编辑{{moduleName}}',
    create: '新建{{moduleName}}',
  },
  deleteModal: {
    delete: '删除',
    info: '删除此{{moduleName}}，将其从 {{count}} 个事项中删除',
    infos: '删除此{{moduleName}}，将其从 {{count}} 个事项中删除',
    item: '{{moduleName}}中的事项',
    items: '{{moduleName}}中的事项',
    move: '将事项移至',
    moves: '将事项移至',
    ignore: '移除{{moduleName}}',
    select: '请选择{{moduleName}}',
    sure: '确定删除该{{moduleName}}吗？',
  },
  releaseModal: {
    release: '发布',
    info: '此{{moduleName}}包含 {{count}} 个未完成的事项',
    infos: '此{{moduleName}}包含 {{count}} 个未完成的事项',
    unresolvedItem: '未完成的事项',
    unresolvedItems: '未完成的事项',
    move: '将未完成的事项移动到',
    moves: '将未完成的事项移动到',
    select: '请选择{{moduleName}}',
    ignore: '忽略未完成的事项',
    ignores: '忽略未完成的事项',
    releaseDate: '发布时间',
    message: '{{count}} 个事项将发布',
    messages: '{{count}} 个事项将发布',
    releaseDateRequired: '请选择发布时间',
  },
  mergeModal: {
    merge: '合并',
    info: '你可以将此{{moduleName}}合并到项目中的另一个{{moduleName}}中。此操作无法撤销',
    mergeTo: '把 {{name}} 合并到',
    select: '请选择{{moduleName}}',
  },
};

export default version;
